#%RAML 0.8
title: Lunch vote system
version: 1.0.0-SNAPSHOT
protocols: [ HTTP ]
baseUri: http://localhost:8080/api
mediaType: application/json
schemas:
  - Restaurants: !include Restaurants.schema.json
  - Restaurant: !include Restaurant.schema.json
  - Error: !include Error.schema.json
securitySchemes:
  - basic:
      description: Basic Authentication
      type: Basic Authentication
/restaurant:
  get:
    description: List of Restaurants
    securedBy: [basic]
    responses:
      200:
        body:
          application/json:
            schema: Restaurants
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
  put:
    description: Create new Restaurant
    securedBy: [basic: { role: ADMIN }]
    body:
      application/json:
        schema: Restaurant
    responses:
      201:
        body:
          application/json:
            schema: Restaurant
        headers:
          Location:
            description: URL of created Restaurant
            type: string
            required: true
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
/restaurant/${id}:
  get:
    description: Get one Restaurant information
    securedBy: [basic]
    responses:
      200:
        body:
          application/json:
            schema: Restaurant
      404:
        description: Restaurant with id not found
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
  delete:
    description: Delete Restaurant by id
    securedBy: [basic: { role: ADMIN }]
    responses:
      200:
        description: Restaurant successfully deleted
      404:
        description: Restaurant with id not found
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
  patch:
    description: Update exists Restaurant with partial JSON information
    securedBy: [basic: { role: ADMIN }]
    body:
      application/json:
        schema: Restaurant
    responses:
      200:
        description: Restaurant successfully patched
        body:
          application/json:
            schema: Restaurant
      404:
        description: Restaurant with id not found
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
  put:
    description: Update exists Restaurant with full JSON information
    securedBy: [basic: { role: ADMIN }]
    body:
      application/json:
        schema: Restaurant
    responses:
      200:
        description: Restaurant successfully updated
        body:
          application/json:
            schema: Restaurant
      404:
        description: Restaurant with id not found
      401:
        description: Authentication is required
        body:
          application/json:
            schema: Error
      403:
        description: Access is denied
        body:
          application/json:
            schema: Error
