language: java

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov
  - curl -sL http://bit.ly/jpm4j >jpm4j.jar
  - java -jar jpm4j.jar --user init
  - ${HOME}/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - ./gradlew jacocoTestReport coveralls
  - codecov
  - ${HOME}/jpm/bin/codacy-coverage-reporter -l Java -r ./build/reports/jacoco/test/jacocoTestReport.xml
  - ./gradlew -Pversioneye.projectid=${VERSION_EYE__PROJECT_ID} -Pversioneye.api_key=${VERSION_EYE__API_KEY} versionEyeUpdate
